apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: argus
spec:
  selector:
    app: sdkjsdf
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
  clusterIP: None
