# neo4j-values.yaml
neo4j:
  name: argus-gdb
  password: mycoolpassword
  resources:
    cpu: "6"
    memory: "2Gi"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
  import:
    mode: defaultStorageClass
    defaultStorageClass:
      accessModes:
        - ReadWriteOnce
      requests:
        storage: 1Gi
auth:
  enabled: true
service:
  type: LoadBalancer
persistentVolumes:
  logs:
    enabled: true
    mountPath: /mnt/argus
    hostPath: /mnt/argus
existingPasswordSecret: "argus-secrets"	
existingPasswordSecretKey: "NEO4J_PASSWORD"
config:
  dbms.directories.plugins: "/plugins"
  dbms.security.procedures.unrestricted: "apoc.cypher.*"
  dbms.security.procedures.allowList: "apoc.*"
  server.directories.plugins: "/var/lib/neo4j/labs"
  server.config.strict_validation.enabled: "false"
env:
  NEO4J_PLUGINS: '["apoc"]'
dbms:
  memory:
    heap:
      initial_size: 2048m
      max_size: 2048m