# neo4j-values.yaml
neo4j:
  name: argus-gdb
  passwordFromSecret: "argus-secrets"
  resources:
    cpu: "4"
    memory: "4Gi"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
  import:
    mode: defaultStorageClass
    defaultStorageClass:
      accessModes:
        - ReadWriteOnce
      requests:
        storage: 1Gi
auth:
  enabled: true
service:
  type: LoadBalancer
persistentVolumes:
  logs:
    enabled: true
    mountPath: /mnt/argus
    hostPath: /mnt/argus
