# neo4j-values.yaml
neo4j:
  name: argus-gdb
  resources:
    cpu: "0.5"
    memory: "2Gi"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
existingPasswordSecret: "argus-secrets"
existingPasswordSecretKey: "NEO4J_PASSWORD"
auth:
  enabled: true
  adminUser: neo4j  # This could be customized
  adminPasswordSecret: "neo4j-secrets"
  adminPasswordKey: "NEO4J_PASSWORD"
